In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
!nvidia-smi

Thu Oct  3 17:42:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##**Introduction to Tensors**
**Creating tensors**
**pytorch tensors :- are created using 'torch.tensor().'**

In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# get tensor back as python int
scaler.item()

7

In [ ]:
scaler.shape

torch.Size([])

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#  MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10],
                       [1,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [ 1, 12]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1][0]

tensor(9)

In [ ]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0], TENSOR[0][0], TENSOR[0][1], TENSOR[0][2],TENSOR[0][0][0],TENSOR[0][0][1],TENSOR[0][0][2]

(tensor([[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]),
 tensor([1, 2, 3]),
 tensor([3, 4, 5]),
 tensor([5, 6, 7]),
 tensor(1),
 tensor(2),
 tensor(3))

##**Random Tensors**

Random tensors are important
beacause the way many neural nets learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

##start with random numbers -> look at  data -> update random num -> look at data -> update rand num .

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim

(tensor([[0.5339, 0.9340, 0.7554, 0.5178],
         [0.2657, 0.8202, 0.3334, 0.5595],
         [0.4191, 0.7407, 0.1728, 0.9775]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [ ]:
# create a random tensor with similar shape to an image tensor.
random_image_size_tensor = torch.rand(size=(5,5,3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim,random_image_size_tensor

(torch.Size([5, 5, 3]),
 3,
 tensor([[[0.1015, 0.5166, 0.0250],
          [0.8965, 0.8143, 0.8709],
          [0.8517, 0.3351, 0.9665],
          [0.6626, 0.8457, 0.7631],
          [0.5375, 0.4899, 0.2091]],
 
         [[0.2278, 0.4896, 0.0990],
          [0.3953, 0.1863, 0.5514],
          [0.1505, 0.4549, 0.4327],
          [0.6681, 0.3815, 0.2359],
          [0.6515, 0.4891, 0.5380]],
 
         [[0.5446, 0.9070, 0.9137],
          [0.0313, 0.9484, 0.0820],
          [0.5390, 0.7675, 0.4999],
          [0.4012, 0.3863, 0.2993],
          [0.9851, 0.9504, 0.9704]],
 
         [[0.7411, 0.5779, 0.8975],
          [0.0627, 0.9820, 0.7566],
          [0.3421, 0.9187, 0.2432],
          [0.8826, 0.5984, 0.5153],
          [0.5798, 0.4123, 0.9858]],
 
         [[0.1884, 0.0593, 0.4359],
          [0.0646, 0.1035, 0.6292],
          [0.4684, 0.9442, 0.3557],
          [0.0259, 0.4018, 0.9092],
          [0.8016, 0.3170, 0.9841]]]))

## **Zeros and ones**

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(3, 4)

In [ ]:
tensor1[:, 0] = 0

# Now multiply them element-wise
result = tensor1 * tensor2

print("Masked Tensor 1:\n", tensor1)
print("Result after multiplication:\n", result)

Masked Tensor 1:
 tensor([[0.0000, 0.0031, 0.6431, 0.0397],
        [0.0000, 0.2437, 0.5430, 0.5577],
        [0.0000, 0.8668, 0.0968, 0.9775]])
Result after multiplication:
 tensor([[0.0000, 0.0026, 0.2678, 0.0180],
        [0.0000, 0.1671, 0.5374, 0.1283],
        [0.0000, 0.2494, 0.0444, 0.2744]])


In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor , random_tensor.dtype

(tensor([[0.5339, 0.9340, 0.7554, 0.5178],
         [0.2657, 0.8202, 0.3334, 0.5595],
         [0.4191, 0.7407, 0.1728, 0.9775]]),
 torch.float32)

##**creating a range of tensors and tensors-like**

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten, one_to_ten.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_ones = torch.ones_like(input=one_to_ten)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

##**Tensor datatypes**

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [ ]:
float_16_tensor2 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
],
                              dtype=torch.float16)
float_16_tensor2, float_16_tensor2.dtype

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], dtype=torch.float16),
 torch.float16)

In [ ]:
float_16_tensor2 * float_32_tensor

tensor([[ 3., 12., 27.],
        [12., 30., 54.],
        [21., 48., 81.]])

In [ ]:
float_32_tensor.shape

torch.Size([3])

In [ ]:
float_16_tensor2.shape

torch.Size([3, 3])

 ## Getting info from the tensors (Tensor attributes).
*   Tensors not right datatypes :- to do get datatype from a tensor, can use tensor.dtype .
*   Tensors not right shape :- To get shape from a tensor, can use tensor.shape.
*   Tensors not on the right device :- to get device from a tensor, can use tensor.device.







In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9778, 0.6632, 0.2536, 0.6581],
        [0.2546, 0.3518, 0.5297, 0.2805],
        [0.9295, 0.8193, 0.8443, 0.3259]])

In [ ]:
# find out the details about the some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9778, 0.6632, 0.2536, 0.6581],
        [0.2546, 0.3518, 0.5297, 0.2805],
        [0.9295, 0.8193, 0.8443, 0.3259]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
some_tensor_16 = some_tensor.type(torch.float16)
some_tensor_16, some_tensor_16.dtype

(tensor([[0.9775, 0.6631, 0.2537, 0.6582],
         [0.2546, 0.3518, 0.5298, 0.2805],
         [0.9297, 0.8193, 0.8442, 0.3259]], dtype=torch.float16),
 torch.float16)

##**Manipulating tensors include:-**


1.   Addition
2.   Subtraction
1.   Multiplication (element wise)
2.   Division
1.   Matrix Multiplication







In [ ]:
# create a tensor and add 10 to it.
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#  Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try pytorch in-built funcs
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

##**Matrix Multiplication**
Two main ways of performing multiplication in neural nets and deeplearning:
1.   Element-wise multiplication
2.   Matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
*  '(3,2) @ (3,4)' this won't work.
*  '(3,2) @ (2,4)' thi will work.




In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 794 µs, total: 794 µs
Wall time: 801 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 36.2 µs


tensor(14)

## To fix shape issue we use **Transpose**  

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A, tensor_B.T) # torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

##**Tensor aggregation**

In [ ]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# finding the positional min and max.

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the position in tensor that has the minimum vakue with atrgmin() -> returns index position of the target tensor where the minimum value occurs.
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, sequeezing and unsqueezing tensors
* Reshaping - reshapes a view of an input tensor to a defined shape.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from the tensor
* unsqueeze - add a '1' dimension to a tensor.
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way.

In [ ]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute() - rearranges the dimensions of target tensor in a specified order
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange  the axis (or dim) order.
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(728218.), tensor(728218.))

##**Indexing (Selecting data from tensors)**

indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index on x tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [ ]:
# you can also use ":" to select "all" of a tensor dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, 0, 0]

tensor([1])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 diemnsion but only the 1 index value of 1st and 2nd dimesion
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimesion and all values of 2nd dimension
x[:, 0, :]

tensor([[1, 2, 3]])

In [ ]:
# index on x to return 9.
print(x[:,2,2])
# index on x to return 3, 6, 9.
print(x[:, :, -1])
# index on x to return 2, 6, 8.
print(x[0,[0,1,2],[1,2,1]])

tensor([9])
tensor([[3, 6, 9]])
tensor([2, 6, 8])


In [ ]:
x[:,:1]

tensor([[[1, 2, 3]]])

## PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing lib.
And because of this, PyTorch has functionality to interact with it.
* Data in numpy, want in pytorch tensor- > "torch.from_numpy(ndarray)".
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)# for floats datatype default for NumPy is float64.
print(f"array: {array} and its data type is '{array.dtype}'")
tensor = torch.from_numpy(array) # for float datatype default for pytorch tensor is float32.
print(f"tensor: {tensor} and pytorch reflects the dtype of the numpy array: {tensor.dtype}")

array: [1. 2. 3. 4. 5. 6. 7.] and its data type is 'float64'
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) and pytorch reflects the dtype of the numpy array: torch.float64


In [ ]:
# we can change the dtype while creating tensor from numpy
tensor = torch.from_numpy(array).type(torch.float32)
print(f"tensor: {tensor} and now the dtype is '{tensor.dtype}'")

tensor: tensor([1., 2., 3., 4., 5., 6., 7.]) and now the dtype is 'torch.float32'


In [ ]:
# change the value of array , what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

* In short how a neural nets learns:

=> 'start with random numbers -> tensor opreations -> update random numbers to ttry and make them better representaions of the data -> again -> again -> ...'

* To reduce the randomness in nn's and pytorch comes the concept of a 'random seed', Essentially what the random seed does id "flavour" the randomness.

In [ ]:
# create two random tansors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7138, 0.2428, 0.6248, 0.2015],
        [0.5552, 0.2088, 0.1486, 0.0860],
        [0.2919, 0.3235, 0.8779, 0.0924]])
tensor([[0.5501, 0.6180, 0.7372, 0.2914],
        [0.8176, 0.4229, 0.3501, 0.8576],
        [0.3274, 0.4573, 0.9109, 0.8671]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensors

# set the random seed
torch.manual_seed(42)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(42)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##**Running tensors and PyTorch objects on the GPUs (and making faster computations)**
GPU's =faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to amke everything hunky dory (good).

##1. Getting a GPU

1.   Easiest - use google colab for a free GPU (options to upgrade well)
2.   Use your own GPU.
3.   use cloud computing- GCP, AWS, Azure, thes services allow you to rent the computers on the cloud and access them.



In [ ]:
!nvidia-smi

Thu Oct  3 17:42:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##**2. check for GPU access with PyTorch**

In [ ]:
#  check for GPU access with pytorch
torch.cuda.is_available()


True

## Setup pytorch device agnostics as it is capable of running compute on GPU or CPU

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#  count nmbers of devices
torch.cuda.device_count()

1

##**3. Putting tensors (and models) on the GPU**

The reason we want our tensor/models on gpu is becoz using a GPU resulta in faster computations.


In [ ]:
# create a tensor (dafault on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# tensor not on GPU
print(tensor)

tensor([1, 2, 3])


Note :- use .to() instead of torch.device(), torch.dttype(), using .to() we can simultaneously move the tensor between CPU <-> GPU and also set different dtype of the tensors.

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##**4. Moving tensors back to the CPU**

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensorx = torch.empty(3,3,3,dtype=torch.int8)
print(tensorx, tensorx.dim())

tensor([[[ 112,  125,  -34],
         [  36,   78,  120],
         [   0,    0,  112]],

        [[ 125,  -34,   36],
         [  78,  120,    0],
         [   0,   32,    0]],

        [[   0,    0,    0],
         [   0,    0,    0],
         [-128,    0,    0]]], dtype=torch.int8) 3


In [ ]:
tensorx.mT

tensor([[[ 112,   36,    0],
         [ 125,   78,    0],
         [ -34,  120,  112]],

        [[ 125,   78,    0],
         [ -34,  120,   32],
         [  36,    0,    0]],

        [[   0,    0, -128],
         [   0,    0,    0],
         [   0,    0,    0]]], dtype=torch.int8)